// CAUTION: THIS IS GENERATED CODE, DO NOT EDIT
// The data is taken from ./bank.csv
// To regenerated this file: in this directory, run this command "go run ./cmd/bank.go"
package vietqr

// VNBankM maps BIN to Bank information
var VNBankM = map[string]Bank{
	"970400": Bank{
		BIN: "970400",
		Name: "TMCP Sài Gòn Công thương",
		ShortName: "SaigonBank",
		Code: "SGICB",
		SWIFTCode: "SBITVNVX",
	},
	"970403": Bank{
		BIN: "970403",
		Name: "TMCP Sài Gòn Thương tín",
		ShortName: "Sacombank",
		Code: "STP",
		SWIFTCode: "SGTTVNVX",
	},
	"970405": Bank{
		BIN: "970405",
		Name: "Nông nghiệp và Phát triển Nông thôn Việt Nam",
		ShortName: "Agribank",
		Code: "VBA",
		SWIFTCode: "VBAAVNVX",
	},
	"970406": Bank{
		BIN: "970406",
		Name: "TMCP Đông Á",
		ShortName: "DongABank",
		Code: "DOB",
		SWIFTCode: "EACBVNVX",
	},
	"970407": Bank{
		BIN: "970407",
		Name: "TMCP Kỹ thương",
		ShortName: "Techcombank",
		Code: "TCB",
		SWIFTCode: "VTCBVNVX",
	},
	"970408": Bank{
		BIN: "970408",
		Name: "Thương mại TNHH MTV Dầu Khí Toàn Cầu",
		ShortName: "GPBank",
		Code: "GPB",
		SWIFTCode: "GBNKVNVX",
	},
	"970409": Bank{
		BIN: "970409",
		Name: "TMCP Bắc Á",
		ShortName: "BacABank",
		Code: "BAB",
		SWIFTCode: "NASCVNVX",
	},
	"970410": Bank{
		BIN: "970410",
		Name: "TNHH MTV Standard Chartered",
		ShortName: "StandardChartered",
		Code: "SCVN",
		SWIFTCode: "SCBLVNVX",
	},
	"970412": Bank{
		BIN: "970412",
		Name: "TMCP Đại chúng Việt Nam",
		ShortName: "PVcomBank",
		Code: "PVCB",
		SWIFTCode: "WBVNVNVX",
	},
	"970414": Bank{
		BIN: "970414",
		Name: "TNHH MTV Đại Dương",
		ShortName: "Oceanbank",
		Code: "Oceanbank",
		SWIFTCode: "OCBKUS3M",
	},
	"970415": Bank{
		BIN: "970415",
		Name: "TMCP Công thương Việt Nam",
		ShortName: "VietinBank",
		Code: "ICB",
		SWIFTCode: "ICBVVNVX",
	},
	"970416": Bank{
		BIN: "970416",
		Name: "TMCP Á Châu",
		ShortName: "ACB",
		Code: "ACB",
		SWIFTCode: "ASCBVNVX",
	},
	"970418": Bank{
		BIN: "970418",
		Name: "Đầu tư và Phát triển Việt Nam",
		ShortName: "BIDV",
		Code: "BIDV",
		SWIFTCode: "BIDVVNVX",
	},
	"970419": Bank{
		BIN: "970419",
		Name: "TMCP Quốc dân",
		ShortName: "NCB",
		Code: "NCB",
		SWIFTCode: "NVBAVNVX",
	},
	"970421": Bank{
		BIN: "970421",
		Name: "liên doanh Việt Nga",
		ShortName: "VRBank",
		Code: "VRB",
		SWIFTCode: "VRBAVNVX",
	},
	"970422": Bank{
		BIN: "970422",
		Name: "TMCP Quân Đội",
		ShortName: "MBBank",
		Code: "MB",
		SWIFTCode: "MSCBVNVX",
	},
	"970423": Bank{
		BIN: "970423",
		Name: "TMCP Tiên Phong",
		ShortName: "TPBank",
		Code: "TPB",
		SWIFTCode: "TPBVVNVX",
	},
	"970424": Bank{
		BIN: "970424",
		Name: "TNHH MTV Shinhan Việt Nam",
		ShortName: "ShinhanBank",
		Code: "SHBVN",
		SWIFTCode: "SHBKVNVX",
	},
	"970425": Bank{
		BIN: "970425",
		Name: "TMCP An Bình",
		ShortName: "ABBank",
		Code: "ABB",
		SWIFTCode: "ABBKVNVX",
	},
	"970426": Bank{
		BIN: "970426",
		Name: "TMCP Hàng Hải",
		ShortName: "MSB",
		Code: "MSB",
		SWIFTCode: "MCOBVNVX",
	},
	"970427": Bank{
		BIN: "970427",
		Name: "TMCP Việt Á",
		ShortName: "VietABank",
		Code: "VAB",
		SWIFTCode: "VNACVNVX",
	},
	"970428": Bank{
		BIN: "970428",
		Name: "TMCP Nam Á",
		ShortName: "NamABank",
		Code: "NAB",
		SWIFTCode: "NAMAVNVX",
	},
	"970429": Bank{
		BIN: "970429",
		Name: "TMCP Sài Gòn",
		ShortName: "SCB",
		Code: "SCB",
		SWIFTCode: "SACLVNVX",
	},
	"970430": Bank{
		BIN: "970430",
		Name: "TMCP Xăng dầu Petrolimex",
		ShortName: "PGBank",
		Code: "PGB",
		SWIFTCode: "PGBLVNVX",
	},
	"970431": Bank{
		BIN: "970431",
		Name: "TMCP Xuất Nhập khẩu Việt Nam",
		ShortName: "Eximbank",
		Code: "EIB",
		SWIFTCode: "EBVIVNVX",
	},
	"970432": Bank{
		BIN: "970432",
		Name: "TMCP Việt Nam Thịnh Vượng",
		ShortName: "VPBank",
		Code: "VPB",
		SWIFTCode: "VPBKVNVX",
	},
	"970433": Bank{
		BIN: "970433",
		Name: "TMCP Việt Nam Thương Tín",
		ShortName: "VietBank",
		Code: "VIETBANK",
		SWIFTCode: "VNTTVNVX",
	},
	"970434": Bank{
		BIN: "970434",
		Name: "TNHH Indovina",
		ShortName: "IndovinaBank",
		Code: "IVB",
		SWIFTCode: "IABBVNVX",
	},
	"970436": Bank{
		BIN: "970436",
		Name: "TMCP Ngoại thương Việt Nam",
		ShortName: "Vietcombank",
		Code: "VCB",
		SWIFTCode: "BFTVVNVX",
	},
	"970437": Bank{
		BIN: "970437",
		Name: "TMCP Phát triển TP.HCM",
		ShortName: "HDBank",
		Code: "HDB",
		SWIFTCode: "HDBCVNVX",
	},
	"970438": Bank{
		BIN: "970438",
		Name: "TMCP Bảo Việt",
		ShortName: "BaoVietBank",
		Code: "BVB",
		SWIFTCode: "BVBVVNVX",
	},
	"970439": Bank{
		BIN: "970439",
		Name: "liên doanh VID PUBLIC BANK",
		ShortName: "PublicBank",
		Code: "PBVN",
		SWIFTCode: "VIDPVNVX",
	},
	"970440": Bank{
		BIN: "970440",
		Name: "TMCP Đông Nam Á",
		ShortName: "SeABank",
		Code: "SEAB",
		SWIFTCode: "SEAVVNVX",
	},
	"970441": Bank{
		BIN: "970441",
		Name: "TMCP Quốc Tế Việt Nam",
		ShortName: "VIB",
		Code: "VIB",
		SWIFTCode: "VNIBVNVX",
	},
	"970442": Bank{
		BIN: "970442",
		Name: "TNHH MTV Hong Leong Việt Nam",
		ShortName: "HongLeong",
		Code: "HLBVN",
		SWIFTCode: "HLBBVNVX",
	},
	"970443": Bank{
		BIN: "970443",
		Name: "TMCP Sài Gòn – Hà Nội",
		ShortName: "SHB",
		Code: "SHB",
		SWIFTCode: "SHBAVNVX",
	},
	"970444": Bank{
		BIN: "970444",
		Name: "Thương mại TNHH MTV Xây dựng Việt Nam",
		ShortName: "CBBank",
		Code: "CBB",
		SWIFTCode: "GTBAVNVX",
	},
	"970446": Bank{
		BIN: "970446",
		Name: "Hợp tác xã Việt Nam",
		ShortName: "COOPBANK",
		Code: "COOPBANK",
		SWIFTCode: "",
	},
	"970448": Bank{
		BIN: "970448",
		Name: "TMCP Phương Đông",
		ShortName: "OCB",
		Code: "OCB",
		SWIFTCode: "ORCOVNVX",
	},
	"970449": Bank{
		BIN: "970449",
		Name: "TMCP Bưu điện Liên Việt (Ngân hàng TMCP Lộc Phát Việt Nam)",
		ShortName: "LPBank",
		Code: "LPB",
		SWIFTCode: "LVBKVNVX",
	},
	"970452": Bank{
		BIN: "970452",
		Name: "TMCP Kiên Long",
		ShortName: "KienLongBank",
		Code: "KLB",
		SWIFTCode: "KLBKVNVX",
	},
	"970454": Bank{
		BIN: "970454",
		Name: "TMCP Bản Việt",
		ShortName: "VietCapitalBank",
		Code: "VCCB",
		SWIFTCode: "VCBCVNVX",
	},
	"970455": Bank{
		BIN: "970455",
		Name: "Công nghiệp Hàn Quốc - Chi nhánh Hà Nội",
		ShortName: "IBKHN",
		Code: "IBKHN",
		SWIFTCode: "IBKOVNVX",
	},
	"970456": Bank{
		BIN: "970456",
		Name: "Industrial Bank of Korea - Chi nhánh Hồ Chí Minh",
		ShortName: "IBKHCM",
		Code: "IBKHCM",
		SWIFTCode: "IBKOVNVX",
	},
	"970457": Bank{
		BIN: "970457",
		Name: "Ngân hàng TNHH Một Thành Viên Woori Bank Việt Nam",
		ShortName: "Woori",
		Code: "WVN",
		SWIFTCode: "HVBKVNVX",
	},
	"970458": Bank{
		BIN: "970458",
		Name: "Ngân hàng TNHH Một Thành Viên UOB Việt Nam",
		ShortName: "UnitedOverseas",
		Code: "UOB",
		SWIFTCode: "UOVBVNVX",
	},
	"970459": Bank{
		BIN: "970459",
		Name: "Ngân hàng TNHH Một Thành Viên CIMB Việt Nam",
		ShortName: "CIMBBank",
		Code: "CIMB",
		SWIFTCode: "CIBBVNVN",
	},
	"970460": Bank{
		BIN: "970460",
		Name: "Công ty Tài chính cổ phần Xi Măng",
		ShortName: "Vietcredit",
		Code: "Vietcredit",
		SWIFTCode: "",
	},
	"970462": Bank{
		BIN: "970462",
		Name: "Ngân hàng Kookmin - Chi nhánh Hà Nội",
		ShortName: "KookminHN",
		Code: "KBHN",
		SWIFTCode: "CZNBVN2X",
	},
	"970463": Bank{
		BIN: "970463",
		Name: "Ngân hàng Kookmin - Chi nhánh Tp. Hồ Chí Minh",
		ShortName: "KookminHCM",
		Code: "KBHCM",
		SWIFTCode: "CZNBVNVX",
	},
	"970464": Bank{
		BIN: "970464",
		Name: "Công ty Tài chính TNHH MTV CỘNG ĐỒNG (TNHH MTV TNEX)",
		ShortName: "TNEXFinance",
		Code: "FCCOM",
		SWIFTCode: "",
	},
	"970465": Bank{
		BIN: "970465",
		Name: "Ngân hàng SINOPAC - Chi nhánh Tp. Hồ Chí Minh",
		ShortName: "SINOPAC",
		Code: "SINOPAC",
		SWIFTCode: "SINOVNVX",
	},
	"970466": Bank{
		BIN: "970466",
		Name: "Ngân hàng KEB HANA - Chi nhánh Tp. Hồ Chí Minh",
		ShortName: "KEBHanaHCM",
		Code: "KEBHANAHCM",
		SWIFTCode: "KOEXVN2X",
	},
	"970467": Bank{
		BIN: "970467",
		Name: "Ngân hàng KEB HANA - Chi nhánh Hà Nội",
		ShortName: "KEBHANAHN",
		Code: "KEBHANAHN",
		SWIFTCode: "KOEXVNVX",
	},
	"970468": Bank{
		BIN: "970468",
		Name: "Công ty Tài chính TNHH MTV Mirae Asset (Việt Nam)",
		ShortName: "MAFC",
		Code: "MAFC",
		SWIFTCode: "",
	},
	"970470": Bank{
		BIN: "970470",
		Name: "Công ty Tài chính TNHH MB SHINSEI",
		ShortName: "MCredit",
		Code: "MCredit",
		SWIFTCode: "",
	},
}